language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"

env:
  - NODE_ENV=test

before_script:
  - npm i -g istanbul coveralls codacy-coverage

script: istanbul cover node_modules/mocha/bin/_mocha test

after_script:
  - cat ./coverage/lcov.info | coveralls
  - cat ./coverage/lcov.info | codacy-coverage
